### ISSUE TITLE
Caighdean Machine Translation provider doesnt use https

### ISSUE THREAD

**Issue by phlax** [kscanne/caighdean#2]
Hi @kscanne we arent currently able to use the mt engine as MLO is https.

Just wondering if it would be possible to provide this.  cheers.

ref https://github.com/translate/pootle/issues/4600

**Comment by kscanne** [comment]
Chatted with Dwayne about this via email - there's no problem technically, but there may be some administrative hurdles to clear if I continue hosting the service at my university. I may move to my own hosting soon.

**Comment by phlax** [comment]
cool, thanks for letting me know, I opened ticket mostly because we are going to be releasing a new Pootle version in the next couple of weeks, and i was hoping we could include.

**Comment by kscanne** [comment]
Requests over https should now work.

**Comment by unho** [comment]
I think they work now. I am saying that because I get exactly the same errors when using HTTP and HTTPS. So I guess this can be now closed.
