### ISSUE TITLE
Add JavaScript client

### ISSUE THREAD

**Issue by unho** [kscanne/caighdean#3]
It would be a nice addition to the others in https://github.com/kscanne/caighdean/tree/master/clients

**Comment by kscanne** [comment]
I agree!  I'll see if I can write something simple and reusable.

**Comment by kscanne** [comment]
I've added a simple JS client pairs with a minimal HTML form.  

https://github.com/kscanne/caighdean/blob/master/clients/client.html

I'm not a JS expert; feedback welcome!
