### ISSUE TITLE
Convert ga-IE and ga_IE language codes on requests to ga

### ISSUE THREAD

**Issue by unho** [kscanne/caighdean#4]
Converting `ga-IE` and `ga_IE` language codes on requests to `ga` (the only one that is currently accepted) might help simplifying clients code.

**Comment by kscanne** [comment]
This should work now.
But it's important to note that the source language parameter should never be set to ga, ga-IE, or ga_IE from a client like Pootle.  The translation engine only works from languages gd or gv _into_ ga, not in the other direction.  Specifying source parameter as "ga" invokes an Irish "standardizer" (a bit like translating from old Irish to new Irish), which isn't relevant here.

**Comment by unho** [comment]
We know. But nevertheless this minor change would make your software more flexible. And perhaps in the future it would be able to work from `ga`/`ga-IE`/`ga_IE` to `gv` or `gd` :)

**Comment by kscanne** [comment]
That's the plan! :D

**Comment by kscanne** [comment]
By the way, it now will accept country codes for the other languages as well; ga-IE, gd-GB, gv-IM, etc. should all work.  Let me know if you have any problems.
