### ISSUE TITLE
No CORS on POST requests

### ISSUE THREAD

**Issue by phlax** [kscanne/caighdean#5]
afaict there is only CORS headers on the GET requests, but the API now requires POST

**Comment by kscanne** [comment]
I'm seeing the correct headers via POST when I test with other clients, or using https://www.hurl.it/

**Comment by phlax** [comment]
my bad - i see the headers too. It seems like we are having an issue with Request headers, we get a `CORS preflight request failed` issue. Ill close this bug now tho

**Comment by phlax** [comment]
incidentally we have now tracked the source of the issue and will enable on mlo asap

**Comment by kscanne** [comment]
That's great, thanks!  Apologies for the GET vs. POST confusion.
